#nanodet-m-1.5x-416
save_dir: workspace/nanodet_m_1.5x_640_360_12-8_LRAug
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.5x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [176, 352, 704]
      out_channels: 128
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 1                    #Number of Classes
      input_channel: 128
      feat_channels: 128
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

class_names: &class_names ['rc_car']    #Please fill in the category names (not include background category)
data:
  train:
    name: XMLDataset
    class_names: *class_names
    img_path: /home/drone_vision/Data/RC_Car_12-8_PASCAL_VOC/images/train  #Please fill in train image path
    ann_path: /home/drone_vision/Data/RC_Car_12-8_PASCAL_VOC/annotations/train    #Please fill in train xml path
    input_size: [640,360] #[w,h]
    keep_ratio: True
    multi_scale: [0.5, 1.1]     #Default [0.4, 1.2]
    pipeline:
      perspective: 0.0
      scale: [0.5, 1.4]         #Default [0.5, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0               #Default 0
      shear: 0
      translate: 0.2            #Default 0.2
      flip: 0.5
      brightness: 0.2           #Default 0.2
      contrast: [0.6, 1.4]      #Default [0.6, 1.4]
      saturation: [0.5, 1.2]    #Default [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: XMLDataset
    class_names: *class_names
    img_path: /home/drone_vision/Data/RC_Car_12-8_PASCAL_VOC/images/val  #Please fill in val image path
    ann_path: /home/drone_vision/Data/RC_Car_12-8_PASCAL_VOC/annotations/val    #Please fill in val xml path
    input_size: [640,360]       #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 8
  batchsize_per_gpu: 50
schedule:
#  resume:
#  load_model: /home/drone_vision/Data/Nanodet_data/nanodet_m_1.5x_416.ckpt
  optimizer:
    name: SGD
    lr: 0.05
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 300
  lr_schedule:
    name: MultiStepLR
    milestones: [180,250,290]
    gamma: 0.1
  val_intervals: 5
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 5

